### ISSUE TITLE
Scoped plugin error

### ISSUE THREAD

**Issue by chrisblossom** [sarbbottam/eslint-find-rules#303]
When using [@typescript-eslint/eslint-plugin](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin) I'm getting the error:

```js
Error: Cannot find module 'eslint-plugin-@typescript-eslint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/chris/github/eslint-config/node_modules/eslint-find-rules/dist/lib/rule-finder.js:68:26
    at Array.forEach (<anonymous>)
    at _getPluginRules (/Users/chris/github/eslint-config/node_modules/eslint-find-rules/dist/lib/rule-finder.js:66:13)
    at new RuleFinder (/Users/chris/github/eslint-config/node_modules/eslint-find-rules/dist/lib/rule-finder.js:104:21)
    at module.exports (/Users/chris/github/eslint-config/node_modules/eslint-find-rules/dist/lib/rule-finder.js:151:10)
    at Object.<anonymous> (/Users/chris/github/eslint-config/node_modules/eslint-find-rules/dist/bin/find.js:33:18)
```

**Comment by sweetlikepete** [comment]
Looks like this is resolved in 3.4.0 - just updated and everything works great now :)

**Comment by ljharb** [comment]
@sweetlikepete in what version of eslint?

**Comment by sweetlikepete** [comment]
5.16.0

**Comment by chrisblossom** [comment]
I ran the tests added in #305 without the code changes and the tests fail on >=5. They do pass on v6 though (unsure why).
