### ISSUE TITLE
Support for ESLint 9.x?

### ISSUE THREAD

**Issue by mockdeep** [sarbbottam/eslint-find-rules#351]
When I run this with ESLint 9.1 I get an error message:

```
ESLintInvalidOptionsError: Invalid Options:
- Unknown options: useEslintrc
    at processOptions (/home/circleci/app/node_modules/eslint/lib/eslint/eslint-helpers.js:839:15)
    at new ESLint (/home/circleci/app/node_modules/eslint/lib/eslint/eslint.js:593:34)
    at /home/circleci/app/node_modules/eslint-find-rules/dist/lib/rule-finder.js:9:20
    at Generator.next (<anonymous>)
    at step (/home/circleci/app/node_modules/eslint-find-rules/dist/lib/rule-finder.js:81:191)
    at /home/circleci/app/node_modules/eslint-find-rules/dist/lib/rule-finder.js:81:437
    at new Promise (<anonymous>)
    at /home/circleci/app/node_modules/eslint-find-rules/dist/lib/rule-finder.js:81:99
    at _getConfigs (/home/circleci/app/node_modules/eslint-find-rules/dist/lib/rule-finder.js:41:17)
    at /home/circleci/app/node_modules/eslint-find-rules/dist/lib/rule-finder.js:47:30 {
  code: 'ESLINT_INVALID_OPTIONS'
```

Are there plans to update it to support the latest ESLint?

**Comment by ljharb** [comment]
Yes, PRs are most welcome.

**Comment by lotmek** [comment]
Just created a PR to support flat configs in v8 https://github.com/sarbbottam/eslint-find-rules/pull/354
